---
apiVersion: v1
kind: Secret
metadata:
  name: my-quarkus-app-5-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/ohthreeinc/backstage-sample-quarkus-app-5-gitops